Update corne.conf
uncommented WS2812_STRIP since it might be the cause of previous error
rgb_underglow.c:252: undefined reference to `__device_dts_ord_129'

Commented CONFIG_GIPO to see if it's irrelevant